//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avatar()
        {
            
        }
    
        public string username { get; set; }
        public string passw { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string raEth { get; set; }
        public string faTy { get; set; }
        public string idTy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvDi> AvDis { get; set; }

        public Avatar(string username, string passw, string name, int age, string raeth, string faty, string idty )
        {
            this.username = username;
            this.passw = passw;
            this.name = name;
            this.age = age;
            this.raEth = raeth;
            this.faTy = faty;
            this.idTy = idty;
        }

    }
}
