//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diversity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharDi
    {
        public int idCharDi { get; set; }
        public Nullable<int> idDi { get; set; }
        public Nullable<int> idC { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual DisabilityType DisabilityType { get; set; }
    }
}
