//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diversity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThotEntities : DbContext
    {
        public ThotEntities()
            : base("name=ThotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avatar> Avatar { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<DisabilityTypes> DisabilityTypes { get; set; }
        public virtual DbSet<FamilyTypes> FamilyTypes { get; set; }
        public virtual DbSet<IdentityTypes> IdentityTypes { get; set; }
        public virtual DbSet<RaceEthnic> RaceEthnic { get; set; }
    }
}
